/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worldofzuul;

/**
 *
 * @author morte
 */
public class ShowMap {
        public static void showMap(){
        System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM         M            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM   344   M   South    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM         M    Main    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM         M    Hall    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" + 
"MMMMMMMMMMM         M            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMM            M           MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMM            M     B8    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMM            M     U140  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMM____________M           MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM         M            MMMMMMMMMMMMMMMMM outside    MMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM   22A   M   North    MMMMMMMMMMMMMMMMM    Tek     MMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM         M   Main     MMMMMMMMMMMMMMMMM____________MMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM         M   Hall     MMMMMM          M            MMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM         M            MMNNNN          M    tek     MMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMM         M            BBBBBB  byg44   M    Hall    MMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMMM           MMMMMM          M            MMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMMM           MMMMMM__________M________    MMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");              
    }    
}
